trigger:
  branches:
    include:
      - main
  paths:
    include:
      - CRM.ICon.Modality/*

variables:
  ROOT: "$(Build.SourcesDirectory)"
  REPOROOT: "$(Build.SourcesDirectory)"
  OUTPUTROOT: "$(REPOROOT)/out"
  solutionPath: 'CRM.ICon.Modality/CRM.ICon.Modality.sln'
  BuildConfiguration: Release
  WindowsContainerImage: 'onebranch.azurecr.io/windows/ltsc2022/vse2022:latest' # for Windows jobs https://aka.ms/obpipelines/containers

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    featureFlags:
      WindowsHostVersion: 1ESWindows2022
    stages:
    - stage: build
      jobs:
      - job: main
        pool:
          type: windows
        variables:
          ob_outputDirectory: '$(OUTPUTROOT)'
        steps:
        - task: DotNetCoreCLI@2
          displayName: 'Restore NuGet Packages'
          inputs:
            command: restore
            projects: ${{ variables.solutionPath }}
            feedsToUse: config
            nugetConfigPath: nuget.config

        - task: DotNetCoreCLI@2
          displayName: "Build .NET project"
          inputs:
            command: "build"
            projects: '**/*.sln'
            arguments: "--configuration Release /clp:ErrorsOnly"

        #Publish Dotnet Core App
        - task: DotNetCoreCLI@2
          displayName: 'Publish Case Service'
          env:
            ob_restore_phase: true
          inputs:
            command: 'publish'
            publishWebProjects: false
            projects: '$(REPOROOT)/CRM.ICon.Modality/*.csproj'
            arguments: '--configuration Release /p:PublishProfile=FolderProfile'
            zipAfterPublish: false

        #Copy Build Files          
        - task: CopyFiles@2
          displayName: 'Copy Files'
          env:
            ob_restore_phase: true
          inputs:
            SourceFolder: '$(REPOROOT)'
            Contents: |
              **\CRM.ICon.Modality\bin\release\net8.0\publish\**\*.json
              **\CRM.ICon.Modality\bin\release\net8.0\publish\**\*.ps1
              **\CRM.ICon.Modality\bin\release\net8.0\publish\**\*.dll
              **\CRM.ICon.Modality\bin\release\net8.0\publish\**\*.exe
              **\CRM.ICon.Modality\bin\release\net8.0\publish\**\*.xml
              **\CRM.ICon.Modality\bin\release\net8.0\publish\**\*.config
            TargetFolder: '$(OUTPUTROOT)/build/'

        #Sign Files
        - task: onebranch.pipeline.signing@1 # https://aka.ms/obpipelines/signing
          displayName: 'Sign output binaries'
          inputs:
            command: 'sign'
            signing_environment: 'azure-ado'
            files_to_sign: '**/*.exe;**/*.dll;**/*.ps1;**/*.xml;**/*.json'
            search_root: '$(OUTPUTROOT)/build/'

        #CodeQl Finalize
        - task: CodeQL3000Finalize@0
          condition: always()
          displayName: 'CodeQL Finalize'

        #Archive Build Files to Zip Artifact
        - task: ArchiveFiles@2
          displayName: 'Archive output files into zip'
          inputs:
            rootFolderOrFile: '$(OUTPUTROOT)/build/CRM.ICon.Modality/bin/release/net8.0/publish'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(OUTPUTROOT)/$(Build.BuildId).zip'
            replaceExistingArchive: true